version: '2'
services:
  tuya-gateway:
    restart: unless-stopped
    container_name: tuya-gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: tuya-gateway:v1.3
    environment:
      - LOGGING_LEVEL=DEBUG
    env_file:
      - secrets.env
    ports:
      - "65080:65080"
