swagger: '2.0'
info:
  title: Tuya Gateway
  version: "1.3"
  description: test
consumes:
  - application/json
produces:
  - application/json
paths:
  /device/status:
    get:
      tags: [Devices]
      operationId: nanotuya.api.get_device_status
      summary: Get the latest device status
      parameters:
        - $ref: '#/parameters/device_id'
      responses:
        200:
          description: Return device status
          schema:
            type: object
            properties:
              functions:
                type: object
  /device/functions:
    get:
      tags: [Devices]
      operationId: nanotuya.api.get_device_functions
      summary: Query the functions supported by the device
      parameters:
        - $ref: '#/parameters/device_id'
      responses:
        200:
          description: Return device functions
          schema:
            type: object
            properties:
              functions:
                type: object
  /device/commands:
    post:
      tags: [Devices]
      operationId: nanotuya.api.post_device_commands
      summary: "
        Send one or more instruction sets. Whether instruction sets can be
        sent simultaneously depends on the product.
      "
      parameters:
        - $ref: '#/parameters/device_id'
        - name: payload
          in: body
          schema:
            $ref: '#/definitions/payload'
      responses:
        200:
          description: Post device commands
          schema:
            type: object
            properties:
              functions:
                type: object
  /ir/remotes:
    get:
      tags: [ IR ]
      operationId: nanotuya.api.get_ir_device_remotes
      summary: Get the list of remotes bound to IR control
      parameters:
        - $ref: '#/parameters/device_id'
      responses:
        200:
          description: Return bound remotes
          schema:
            type: object
            properties:
              functions:
                type: object
  /ir/keys:
    get:
      tags: [ IR ]
      operationId: nanotuya.api.get_ir_remote_keys
      summary: Get the list of keys bound to the remote of the IR device
      parameters:
        - $ref: '#/parameters/device_id'
        - $ref: '#/parameters/remote_id'
      responses:
        200:
          description: Return keys bound to remote
          schema:
            type: object
            properties:
              functions:
                type: object
    post:
      tags: [ IR ]
      operationId: nanotuya.api.post_ir_remote_key
      summary: Send native or custom (learned) command to IR remote
      parameters:
        - $ref: '#/parameters/device_id'
        - $ref: '#/parameters/remote_id'
        - name: payload
          in: body
          schema:
            $ref: '#/definitions/payload'
      responses:
        200:
          description: Post IR key
          schema:
            type: object
            properties:
              functions:
                type: object
parameters:
  device_id:
    name: device_id
    description: Tuya device unique identifier
    in: query
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"
  remote_id:
    name: remote_id
    description: Tuya IR remote unique identifier
    in: query
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  payload:
    description: Request body with commands for Tuya device
    type: object