name: Docker
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: beerhead/tuya-gateway
          add_git_labels: true
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          platforms: linux/amd64

