name: cicd
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          labels: 'tuya,gateway,api'
          platforms: linux/armv7l
